ALTER TABLE `projetos_materiais`
  ADD COLUMN `plannedQty` DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN `issuedQty` DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN `consumedQty` DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN `returnedQty` DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN `wasteQty` DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN `damagedQty` DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN `lostQty` DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN `plannedUnitCost` DECIMAL(12,4) NULL,
  ADD COLUMN `actualUnitCost` DECIMAL(12,4) NULL,
  ADD COLUMN `varianceCost` DECIMAL(14,4) NOT NULL DEFAULT 0,
  ADD COLUMN `leftoverQty` DECIMAL(12,4) NOT NULL DEFAULT 0;