import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    // Barrel (backward-compatible)
    'index': 'src/index.ts',
    // Individual components
    'button': 'src/components/button.tsx',
    'card': 'src/components/card.tsx',
    'badge': 'src/components/badge.tsx',
    'input': 'src/components/input.tsx',
    'label': 'src/components/label.tsx',
    'textarea': 'src/components/textarea.tsx',
    'checkbox': 'src/components/checkbox.tsx',
    'switch': 'src/components/switch.tsx',
    'select': 'src/components/select.tsx',
    'separator': 'src/components/separator.tsx',
    'popover': 'src/components/popover.tsx',
    'progress': 'src/components/progress.tsx',
    'dialog': 'src/components/dialog.tsx',
    'alert-dialog': 'src/components/alert-dialog.tsx',
    'dropdown-menu': 'src/components/dropdown-menu.tsx',
    'tabs': 'src/components/tabs.tsx',
    'table': 'src/components/table.tsx',
    'form': 'src/components/form.tsx',
    'calendar': 'src/components/calendar.tsx',
    'date-range-picker': 'src/components/date-range-picker.tsx',
    'toast': 'src/components/toast.tsx',
    'toaster': 'src/components/toaster.tsx',
    'loading': 'src/components/loading.tsx',
    'empty-state': 'src/components/empty-state.tsx',
    'page-header': 'src/components/page-header.tsx',
    'module-page-header': 'src/components/module-page-header.tsx',
    'breadcrumbs': 'src/components/breadcrumbs.tsx',
    'stat-card': 'src/components/stat-card.tsx',
    'finance-card': 'src/components/finance-card.tsx',
    'hero-section': 'src/components/hero-section.tsx',
    'data-table-header': 'src/components/data-table-header.tsx',
    'advanced-pagination': 'src/components/advanced-pagination.tsx',
    'stock-badge': 'src/components/stock-badge.tsx',
    'avatar': 'src/components/avatar.tsx',
    'confirm-dialog': 'src/components/confirm-dialog.tsx',
    'form-container': 'src/components/form-container.tsx',
    'form-error': 'src/components/form-error.tsx',
    'auth-input': 'src/components/auth-input.tsx',
    'auth-password': 'src/components/auth-password.tsx',
    'password-input': 'src/components/password-input.tsx',
    'text-input': 'src/components/text-input.tsx',
    'submit-button': 'src/components/submit-button.tsx',
    'logout-button': 'src/components/logout-button.tsx',
    'optimized-image': 'src/components/optimized-image.tsx',
    'pdfexport-button': 'src/components/pdfexport-button.tsx',
    'signature-pad': 'src/components/signature-pad.tsx',
    'proposal-signature-pad': 'src/components/proposal-signature-pad.tsx',
    // Utilities
    'utils': 'src/utils/index.ts',
    'tokens': 'src/tokens/index.ts',
    'types': 'src/types/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: true,
  tsconfig: 'tsconfig.json',
  splitting: true,
  sourcemap: true,
  clean: true,
  banner: {
    js: "'use client';"
  },
  external: [
    'react',
    'react-dom',
    'next',
    'next/image',
    'next/link',
    'next/navigation',
    '@radix-ui/*',
    'class-variance-authority',
    'clsx',
    'lucide-react',
    'tailwind-merge',
    'tailwindcss',
    'react-day-picker',
    'react-hook-form',
    'jspdf',
    'html2canvas',
    '@tanstack/react-table',
  ]
})
