ALTER TABLE `Invoice`
  ADD COLUMN `pdfStorageKey` VARCHAR(255) NULL,
  ADD COLUMN `pdfFileName` VARCHAR(255) NULL,
  ADD COLUMN `pdfGeneratedAt` DATETIME(3) NULL,
  ADD COLUMN `pdfSizeBytes` INTEGER NULL,
  ADD COLUMN `pdfMimeType` VARCHAR(100) NULL,
  ADD COLUMN `pdfSha256` CHAR(64) NULL;
